fable-compiler/fable-browser

README.md
Easy to copy package names and NuGet links with version directly in the readme
I didn't find this information in an easy accessible place when I searched for it so I added it.
=> Add NuGet links and package names to readme

Build.fsx, README.md, src/Geolocation/Browser.Geolocation.fs, src/Geolocation/Browser.Geolocation.fsproj, src/Geolocation/README.md, src/Geolocation/RELEASE_NOTES.md, src/Navigator/Browser.Navigator.fs, src/Navigator/Browser.Navigator.fsproj, src/Navigator/README.md, src/Navigator/RELEASE_NOTES.md, src/Worker/Browser.Worker.fs, src/Worker/Browser.Worker.fsproj, src/Worker/README.md, src/Worker/RELEASE_NOTES.md
Fixes #10 (cc @forki) #15 
As most of the properties in the navigator object are experimental I opted for marking them as `option` so users need to check if they actually exist or not. Please note that (to avoid the dependency with the Browser.Dom package) `navigator` is exposed as a global value instead of a `window` property.
I left several `TODO`s. It'd be great if someone could review and fill the gaps using MDN documentation and the [old bindings](https://github.com/fable-compiler/fable-import/blob/master/Browser/Fable.Import.Browser.fs).
Beta versions of the new packages have already been pushed.
=> [WIP] Add Navigator package

src/Blob/Browser.Blob.fs, src/Dom/Browser.Dom.Ext.fs, src/Dom/Browser.Dom.fsproj, src/XMLHttpRequest/Browser.XMLHttpRequest.fs, src/XMLHttpRequest/Browser.XMLHttpRequest.fsproj
Related to https://github.com/fable-compiler/fable-fetch/issues/4
@MangelMaxime I moved `FormData` to the Blob package, could you please review? A couple of other changes:
- I added overloads for `append` and `set` for string or Blob, but not sure what do with the retrieving methods like `getAll`, `entries` or `values`.
- I've added the constructor overload accepting `HTMLFormElement` as an extension in the Dom package.
=> Move FormData to Blob package

src/WebRTC/Browser.WebRTC.fs, src/WebRTC/RELEASE_NOTES.md
Fix `RTCIceCandidate.ip` as string option
Fix `RTCRtpSender.setStreams` should return a promise
Fix `RTCPeerConnection.setLocalDescription` parameter is mandatory
Fix `RTCPeerConnection.setRemoteDescription` parameter is mandatory
Fix `RTCPeerConnection.addIceCandidate` parameter is mandatory
Fix `RTCPeerConnection.addTrack` stream parameter is an array of `MediaStream`
Fix `RTCPeerConnection.addTransceiver` init parameter is type of type `RTCRtpTransceiverInit`
=> WebRTC stable release

src/MediaStream/Browser.MediaStream.fs, src/MediaStream/RELEASE_NOTES.md
Clone track returns track of the same type
Fix `MediaStream.create` overloads
Set framerate as optional parameter in `HTMLCanvasElement.captureStream`
=> MediaStream stable release

src/WebRTC/Browser.WebRTC.fs, src/WebRTC/Browser.WebRTC.fsproj, src/WebRTC/RELEASE_NOTES.md
`getStates` -> `getStats`.
And add missing [`getStats`](https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnection/getStats) method in RTCPeerConnection. 
@alfonsogarciacaro if everything is okay I could push a NuGet.
=> Fix typo in RTCRtpSender and add missing getStats method in RTCPeerConnection

src/WebRTC/Browser.WebRTC.fs, src/WebRTC/Browser.WebRTC.fsproj, src/WebRTC/RELEASE_NOTES.md
`RTCIceCandidateStats.protocol` accepts only `udp` or `tcp` so it could be specified as `RTCIceProtocol` instead of a string.
[Documentation](https://developer.mozilla.org/en-US/docs/Web/API/RTCIceCandidateStats/protocol)
CC: @MangelMaxime
=> RTCIceCandidateStats.protocol as RTCIceProtocol instead of string.

src/XMLHttpRequest/Browser.XMLHttpRequest.fs
Why is `XMLHttpRequestUpload` commented out?
=> Add XMLHttpRequestUpload

src/Dom/Browser.Dom.fs, src/Event/Browser.Event.fs, src/Svg/Browser.Svg.fs
Working with @TylerHartwig on a problem we found that the `EventTarget` types' `addEventListener` didn't have an overload for the variant that takes a set of listener options as seen [here](https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/removeEventListener).
So I added these overloads.
While doing this, I started looking for other uses/definitions of the `addEventListener` member and saw _a ton_ of them on the SVG types, which shouldn't be necessary as long as those types derive from an interface that eventually derives from `EventTarget`, which I do believe they all do.
=> add eventtarget overload and remove extraneous eventtarget members from svg types

src/MediaStream/Browser.MediaStream.fs, src/MediaStream/RELEASE_NOTES.md
Some breaking changes due to renaming types and fixing some type definitions.
Add `ImageMediaTrackConstraintSet`
Fix ContrainXXX should allow single value or constrain object
Fix some bad type names
Set `MediaTrackCapabilities` properties optional
Add strongly typed methods on `AudioMediaStreamTrack` and `VideoMediaStreamTrack`
Set `MediaDeviceInfo` kind as an enum
=> Add new APIs to MediaStream

src/WebRTC/Browser.WebRTC.fs, src/WebRTC/RELEASE_NOTES.md
`RTCIceCandidateStats.relayProtocol` accepts only `udp`/`tls` or `tcp` so it could be specified as `RTCRelayProtocol` instead of a string.
[Documentation](https://developer.mozilla.org/en-US/docs/Web/API/RTCIceCandidateStats/relayProtocol)
CC: @MangelMaxime
=> RTCIceCandidateStats.relayProtocol as RTCRelayProtocol instead of string

src/Navigator/Browser.Navigator.fs, src/Navigator/RELEASE_NOTES.md
Clipboard read/write text is an useful addition. 
https://developer.mozilla.org/en-US/docs/Web/API/Clipboard#Clipboard_availability
Still, I'm not sure about supporting the other methods, they're experimental, but the text methods should work.
https://www.w3.org/TR/clipboard-apis/#async-clipboard-api
=> Adds the Clipboard API.

src/Dom/Browser.Dom.fs, src/Dom/RELEASE_NOTES.md
Fixes: #52 
PR adds:
- [decodeURIComponent](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/decodeURIComponent),
- [encodeURIComponent](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURIComponent),
- [decodeURI](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/decodeURI),
- [encodeURI](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURI)
=> #52 add missing URI functions

src/Dom/Browser.Dom.fs
The event handlers related to the clipboard API are missing from Document. This PR adds them.
see: https://developer.mozilla.org/en-US/docs/Web/API/Document#clipboard_events
=> Add missing Document event handlers: oncopy, oncut, onpaste

src/Dom/Browser.Dom.fs
Correct event types on HTMLElement for event handlers of the Clipboard API.
=> Clipboard api fixes

src/Event/Browser.Event.fs
Addresses #65 
**Offtopic**
Also, not related with this PR, can we make the global.json
```jsonc
{
"sdk": {
"version": "3.1.300",
"rollForward": "major" // <- major instead of minor
}
}
```
so we can build it with .NET5 as well?
=> Make CustomEvent Generic

src/Dom/Browser.Dom.fs, src/MediaQueryList/Browser.MediaQueryList.fs, src/Navigator/Browser.Navigator.fs, src/Svg/Browser.Svg.fs, src/WebSocket/Browser.WebSocket.fs
New attempt at https://github.com/fable-compiler/fable-browser/pull/79, except replacing ``'Out`` with ``unit`` instead of ``obj`` as per code review.
=> Remove usages of non-existant generic parameters (redone)

README.md, src/MediaRecorder/Browser.MediaRecorder.fsproj
These are changes from publishing the Fable.Browser.MediaRecorder package to Nuget, as discussed on the initial PR: #82
=> Published MediaRecorder

src/Dom/Browser.Dom.fs, src/Dom/Browser.Dom.fsproj, src/Dom/RELEASE_NOTES.md
This PR will add [`orientation`](https://developer.mozilla.org/en-US/docs/Web/API/ScreenOrientation) to `window.screen` object.
=> Fix #89: Add `orientation` to `window.screen`

src/Dom/Browser.Dom.fs
This adds support for `Element.toggleAttribute`.
As I don't know much javascript tbh (thank you Fable❤), I am not sure whether the `??` operator is too 'modern' to use.
=> Browser.Dom: add support for Element.toggleAttribute

src/MediaRecorder/Browser.MediaRecorder.fs
https://developer.mozilla.org/en-US/docs/Web/API/MediaRecorder/isTypeSupported
=> MediaRecorder.isTypeSupported

src/Dom/Browser.Dom.fs, src/Dom/RELEASE_NOTES.md
I would like to expose https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/imageSmoothingEnabled to the CanvasRenderingContext2D.
I am very new to fable and honestly not too sure how this should be done, found an old issue on https://github.com/fable-compiler/Fable/issues/644#issuecomment-271911365 and it worked to use the dynamic call as described there with
```
open Fable.Core.JsInterop
ctx?imageSmoothingEnabled <- false
```
The issue mentioned something about upgrading ```ts2fable```, so there are perhaps better way to expose this, but that was from 2017.
I tried to follow similar changes as in https://github.com/fable-compiler/fable-browser/commit/e091f8b20ee432b5dafee3459a8ac47d48d445da#diff-91d379c5b101345f00a814c5f4a2406e862cc022df4c4d6d9183c86e66aac8a5to add …
=> Expose imageSmoothingEnabled on CanvasRenderingContext2D

src/Dom/Browser.Dom.fs
This adds the [HTMLDialogElement](https://developer.mozilla.org/en-US/docs/Web/API/HTMLDialogElement) API.
I did not add constructors (i.e., `HTMLDialogElement.Create`), as there are none.
This is in contrast to, for example, `HTMLDivElement.Create` which is not valid JS.
Should I add one anyways?
=> Add HTMLDialogElement API

src/Dom/Browser.Dom.fs
https://github.com/fable-compiler/fable-browser/pull/92 seems to have intended to add `reportValidity` to `HTMLInputElement` but added it to `HTMLButtonElement`. This PR moves the function to `HTMLInputElement` and also adds it to `HTMLFormElement` according to https://developer.mozilla.org/en-US/docs/Web/API/HTMLFormElement/reportValidity.
=> Move report validity function to appropriate places

src/Dom/Browser.File.fs
`File` inherits `Blob` which already has a `.text()` method. [MDN](https://developer.mozilla.org/en-US/docs/Web/API/File).
Also, the current abstract `text` field on `File` does not get compiled into a method call, but rather a field access.
=> Remove unnecessary/broken .text field from File

src/MediaRecorder/Browser.MediaRecorder.fs
Fixes #118.
`uint32` is used throughout `Browser.MediaStream`, so I decided to stick with unsigned.
=> Change MediaRecorder properties from uint64 to uint32

src/Css/Browser.Css.fs
Adds some missing properties to `CSSStyleDeclaration`.
References:
- https://www.w3.org/TR/css-grid-1/#property-index
- https://drafts.csswg.org/css-align/#gap-shorthand
=> Add CSS grid and gap style properties

src/Dom/Browser.Dom.fs
[As per MDN](https://developer.mozilla.org/en-US/docs/Web/API/Element/children), the `children` property lives on `Element`, not `HTMLElement`.
=> Move `children` from `HTMLElement` to `Element`

Browser.sln, build.fsx, src/EventSource/Browser.EventSource.fs, src/EventSource/Browser.EventSource.fsproj
As per issue #134 this PR adds [EventSource API](https://developer.mozilla.org/en-US/docs/Web/API/EventSource) support to Fable.
=> Add EventSource API support

src/Dom/Browser.Dom.fs, src/Dom/RELEASE_NOTES.md, src/Event/Browser.Event.fs, src/Event/RELEASE_NOTES.md
- Added few new events
- Added some missing fields for some events
- Removed some non-existing fields from other events
=> Cleaned up and improve number of DOM events

src/Dom/Browser.Dom.fs
Adds the following missing Node methods:
- after
- append
- before
- prepend
=> Add missing Node insertion methods
